### ISSUE TITLE
Dropout rate `drop` is `None` during inference, which causes error in spaCy 2.1

### ISSUE THREAD

**Issue by tokestermw** [explosion/thinc#103]
Hi, this is the exact same issue as: https://github.com/explosion/spaCy/issues/2684

When I run `TextCategorizer` with `pretrained_dims=300`, `drop` becomes `None` during inference, which causes an error:

```python
  File "/Users/thomasopsomer/Envs/spacy-nightly/lib/python3.6/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "<stdin>", line 15, in concatenate_lists_fwd
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'
```

I'm thinking we can change the `drop` to `0.0` as a fix:

https://github.com/explosion/thinc/commit/23174bdf773cae891cbdc8c10bb1f84a37e0f61b

**Comment by honnibal** [comment]
Just making sure, is this still current? Based on the line numbers and the paths there it looks like this might be referring to an old version?

**Comment by tokestermw** [comment]
The quoted code snippet is from an old issue.

I re-created the error with Python 3.6, spaCy 2.1.4, and Thinc 7.0.8. I downloaded `en_core_web_md`.

```
> pip freeze

attrs==19.1.0
blis==0.2.4
certifi==2019.6.16
chardet==3.0.4
cymem==2.0.2
en-core-web-md==2.1.0
idna==2.8
jsonschema==3.0.1
murmurhash==1.0.2
numpy==1.16.4
plac==0.9.6
preshed==2.0.1
pyrsistent==0.15.3
requests==2.22.0
six==1.12.0
spacy==2.1.4
srsly==0.0.7
thinc==7.0.8
tqdm==4.32.2
urllib3==1.25.3
wasabi==0.2.2
```

I created a file called `delete.py`.

```python
import spacy
from spacy.pipeline import TextCategorizer
from spacy.gold import GoldParse

nlp = spacy.load("en_core_web_md")
textcat = TextCategorizer(nlp.vocab, pretrained_dims=300)

for label in ["cat_1", "cat_2", "cat_3"]:
    textcat.add_label(label)

nlp.add_pipe(textcat)

doc = nlp.tokenizer("Apple builds Iphones.")
cats = {"cat_1": True, "cat_2": False, "cat_3": True}
gold = GoldParse(doc, cats=cats)
with nlp.disable_pipes(*["ner", "tagger", "parser"]):
    optimizer = nlp.begin_training()
    losses = {}
    nlp.update([doc], [gold], sgd=optimizer, drop=0.2, losses=losses)

# inference
nlp("Apple builds Iphones.").cats
```

And then I ran `python delete.py`

```
> python delete.py

Traceback (most recent call last):
  File "delete.py", line 22, in <module>
    nlp("Apple builds Iphones.").cats
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/spacy/language.py", line 390, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "pipes.pyx", line 907, in spacy.pipeline.pipes.TextCategorizer.__call__
  File "pipes.pyx", line 920, in spacy.pipeline.pipes.TextCategorizer.predict
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 169, in __call__
    return self.predict(x)
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/thinc/neural/_classes/feed_forward.py", line 40, in predict
    X = layer(X)
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 169, in __call__
    return self.predict(x)
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 133, in predict
    y, _ = self.begin_update(X, drop=None)
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/thinc/api.py", line 163, in begin_update
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/thinc/api.py", line 163, in <listcomp>
    values = [fwd(X, *a, **k) for fwd in forward]
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/thinc/api.py", line 256, in wrap
    output = func(*args, **kwargs)
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/Users/mwu/venv-tmp/lib/python3.6/site-packages/spacy/_ml.py", line 679, in concatenate_lists_fwd
    drop *= drop_factor
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'
```

**Comment by potatochip** [comment]
Also experiencing this in 2.1.7

**Comment by svlandeg** [comment]
Could you both try again with spaCy 2.2.1 ? Looking at the function this error refers to, https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L803 shows that on the current master branch, there is an explicit check for `drop is not None`.

Also, the code snippet by @tokestermw  runs without error for me.
