### ISSUE TITLE
Error when running question text-pair siamese example

### ISSUE THREAD

**Issue by geledek** [explosion/thinc#26]
MacOS
Python 3.6

```
% python examples/text-pair/glove_mwe_multipool_siamese.py
{'rest_api_url': None, 'ws_api_url': None, 'job_id': None, 'quiet': False, 'out_loc': None, 'use_gpu': False, 'L2': 0.0, 'pieces': 3, 'nb_epoch': 30, 'pooling': 'mean+max', 'dropout_decay': 0.0, 'dropout': 0.0, 'max_batch_size': 128, 'min_batch_size': 128, 'depth': 2, 'width': 50, 'dataset': 'quora'}
Load spaCy
Construct model
Traceback (most recent call last):
  File "examples/text-pair/glove_mwe_multipool_siamese.py", line 216, in <module>
    plac.call(main)
  File "/Users/user/anaconda2/envs/py3/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/user/anaconda2/envs/py3/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "examples/text-pair/glove_mwe_multipool_siamese.py", line 155, in main
    >> Residual(Maxout(width*2, pieces=pieces)**2)
  File "/Users/user/anaconda2/envs/py3/lib/python3.6/site-packages/thinc/neural/_classes/resnet.py", line 68, in __init__
    self.Block(width, width, name='rb1-%s' % self.name, **kwargs),
  File "/Users/user/anaconda2/envs/py3/lib/python3.6/site-packages/thinc/neural/_classes/resnet.py", line 26, in __init__
    BatchNorm(name='%s-bn1' % self.name),
TypeError: __init__() missing 1 required positional argument: 'child'
```

I dig into the `_classes/resnet.py` file but couldn't find any postional argument: 'child'.

Am I missing anything?

**Comment by honnibal** [comment]
Should be fixed now.
