### ISSUE TITLE
v6.6.0 setup.py iteritems() error

### ISSUE THREAD

**Issue by telesphore** [explosion/thinc#27]
Python 3.6.1 virtual environment (not conda!), Ubuntu 17.04 x64, GPU cuda 8.0...

I believe that you can stop the error at [line 157 in setup.py](https://github.com/explosion/thinc/blob/master/setup.py#L157) to something like

```
for k, v in cudaconfig.items():
```

Error follows

```
(venv) $ pip list -o
Package Version Latest Type 
------- ------- ------ -----
thinc   6.5.2   6.6.0  sdist
```
```
(venv) $ pip install -U thinc
Collecting thinc
  Using cached thinc-6.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-62_23xac/thinc/setup.py", line 163, in <module>
        CUDA = locate_cuda()
      File "/tmp/pip-build-62_23xac/thinc/setup.py", line 157, in locate_cuda
        for k, v in cudaconfig.iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-62_23xac/thinc/
```

**Comment by honnibal** [comment]
This was dumb, thanks --- the Travis tests didn't exercise the CUDA branch, so this slipped through.
