### ISSUE TITLE
ModuleNotFoundError: No module named 'thinc.neural.util'

### ISSUE THREAD

**Issue by dbl001** [explosion/thinc#49]
I installed spaCy on my Mac OSX 10.11.6 into an Anaconda Python 3.6 environment with conda.
I also was able to build thinc from source with 'fab'.

```
$ conda --version
conda 4.3.29
$ python --version
Python 3.6.3
$ fab --version
Fabric 1.14.0
Paramiko 2.3.1

```
When I try to install the spaCy model I get this error:
```
 python -m sense2vec.download

```

ModuleNotFoundError: No module named 'thinc.neural.util'

I see util.py in thinc.neural package on github.  There must be a conflict or version mismatch
with what I downloaded from conda and what is in the latest version of 'thinc' on github.
Any ideas?

From Conda:
spacy: 2.0.4-py36_0  conda-forge
 thinc: 6.10.0-py36_0 conda-forge

```
$ conda list thinc
# packages in environment at /Users/davidlaxer/anaconda/envs/py36:
#
thinc                     6.10.2                    <pip>
thinc                     6.10.0                   py36_0    conda-forge
thinc                     5.0.8                     <pip>
(py36) David-Laxers-MacBook-Pro:sense2vec davidlaxer$ conda list spacy
# packages in environment at /Users/davidlaxer/anaconda/envs/py36:
#
spacy                     2.0.5                     <pip>
spacy                     2.0.4                    py36_0    conda-forge
spacy                     0.101.0                   <pip>
(py36) David-Laxers-MacBook-Pro:sense2vec davidlaxer$ python -m spacy validate
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/site-packages/spacy/cli/link.py", line 7, in <module>
    from ..compat import symlink_to, path2str
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/site-packages/spacy/compat.py", line 11, in <module>
    from thinc.neural.util import copy_array
ModuleNotFoundError: No module named 'thinc.neural.util'


```

**Comment by dbl001** [comment]
I tried removing the conda and pip installation:
```
$ conda list spacy
# packages in environment at /Users/davidlaxer/anaconda:
#
```
Than installing 'spaCy' from github:
$ python setup.py install

The install worked but I still can't validate or install the model
```
$ python -m spacy.en.download
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/davidlaxer/anaconda/envs/py36/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/davidlaxer/spaCy/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Users/davidlaxer/spaCy/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Users/davidlaxer/spaCy/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/Users/davidlaxer/spaCy/spacy/cli/link.py", line 7, in <module>
    from ..compat import symlink_to, path2str
  File "/Users/davidlaxer/spaCy/spacy/compat.py", line 11, in <module>
    from thinc.neural.util import copy_array
ModuleNotFoundError: No module named 'thinc.neural.util'
```
I can run tests in 'thinc':
```
$ fab eg.mnist
[localhost] local: python examples/mnist_mlp.py
Downloading data from https://s3.amazonaws.com/img-datasets/mnist.pkl.gz
66.7266729019 0.960333333333 0.3                                                
25.7787869463 0.970833333333 0.3                                                
18.8024897413 0.975333333333 0.3                                                
15.2940811263 0.978666666667 0.3                                                
12.6868923288 0.979666666667 0.3                                                
10.907709888 0.979 0.3                                                          
9.90145768215 0.980166666667 0.3                                                
9.58847966164 0.979166666667 0.3                                                
8.16073693893 0.980666666667 0.3                                                
7.54027050765 0.981 0.3                                                         
7.05141087245 0.981333333333 0.3                                                
6.45005679891 0.981166666667 0.3                                                
5.91079736613 0.982666666667 0.3                                                
5.49958813231 0.9835 0.3                                                        
5.22847711169 0.983666666667 0.3                                                
4.99858748966 0.982833333333 0.3                                                
5.0555315372 0.983666666667 0.3                                                 
4.69916855313 0.983166666667 0.3                                                
4.59268881318 0.983166666667 0.3                                                
4.06976232603 0.982166666667 0.3                                                
4.05801555403 0.981666666667 0.3                                                
3.6813617148 0.982 0.3                                                          
4.0125010367 0.983 0.3                                                          
 46%|████████████████▋                   | 2508
```

**Comment by malcolmgreaves** [comment]
I have encountered this same exact error. This only comes up on OS X. Doing a `conda install` of `spacy=2` on linux (specifically ubuntu 16.04.*) is fine. 

Interestingly enough, this error does not come up when building `spacy` from sources on OS X. Could this perhaps be a conda packaging error wrt. OS X?

**Comment by dbl001** [comment]
Good question.  I’m not sure.  The Spacy team indicated they were making major changes.  Perhaps there are inconsistencies  with Conda on OS X.

**Comment by honnibal** [comment]
@malcolmgreaves Is this fixed for spaCy v2.0.8 and v2.0.9?

**Comment by userofgithub1** [comment]
@honnibal I have spaCy 2.0.11 and facing the same problem only when using Spyder the error doesn't appear in terminal. So, I guess not.

**Comment by dbl001** [comment]
Still having issue: 
```
Traceback (most recent call last):
  File "/Users/davidlaxer/Lda2vec-Tensorflow/lda2vec/nlppipe.py", line 3, in <module>
    import spacy
  File "/Users/davidlaxer/anaconda/envs/spacy/bin/python-3.6/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Users/davidlaxer/anaconda/envs/spacy/bin/python-3.6/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Users/davidlaxer/anaconda/envs/spacy/bin/python-3.6/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>
    from .link import link
  File "/Users/davidlaxer/anaconda/envs/spacy/bin/python-3.6/lib/python3.6/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..compat import symlink_to, path2str
  File "/Users/davidlaxer/anaconda/envs/spacy/bin/python-3.6/lib/python3.6/site-packages/spacy/compat.py", line 9, in <module>
    from thinc.neural.util import copy_array
  File "/Users/davidlaxer/anaconda/envs/spacy/bin/python-3.6/lib/python3.6/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/Users/davidlaxer/anaconda/envs/spacy/bin/python-3.6/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer
  File "/Users/davidlaxer/anaconda/envs/spacy/bin/python-3.6/lib/python3.6/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay
  File "optimizers.pyx", line 13, in init thinc.neural.optimizers
  File "ops.pyx", line 1, in init thinc.neural.ops
ImportError: murmurhash.mrmr does not export expected C function hash128_x86

Process finished with exit code 1
```

**Comment by userofgithub1** [comment]
I solved the problem by updating Spyder.

**Comment by lingvisa** [comment]
I have the latest version of Spacy on Mac and tried to compile spacy from source. The compiling is fine, but can't import:
```
 ipython
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import spacy                                                                                                                                                                                                   
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-76a01d9c502b> in <module>
----> 1 import spacy

~/anaconda3/test/spacy/spaCy/spacy/__init__.py in <module>
      8 
      9 # These are imported as part of the API
---> 10 from thinc.neural.util import prefer_gpu, require_gpu
     11 
     12 from . import pipeline

ModuleNotFoundError: No module named 'thinc'


```

I can do everything right without using conda.
