### ISSUE TITLE
Error when running question text-pair examples

### ISSUE THREAD

**Issue by patvdleer** [explosion/thinc#52]
after updating the import models from the predict example

~~~python
from thinc.neural import Model
from thinc.neural._classes.softmax import Softmax
from thinc.neural._classes.maxout import Maxout
from thinc.neural._classes.convolution import ExtractWindow

from thinc.neural.pooling import Pooling, mean_pool, max_pool
from thinc.neural._classes.static_vectors import StaticVectors

from thinc.neural._classes.embed import Embed
from thinc.neural._classes.difference import Siamese, CauchySimilarity
from thinc.neural.util import to_categorical

from thinc.api import layerize, with_flatten, with_getitem, flatten_add_lengths, get_word_ids
from thinc.api import add, chain, clone, concatenate, Arg

from thinc.extra import datasets
from thinc.extra.load_nlp import get_spacy, get_vectors
~~~

I keep getting the following with both the text-pair examples:

~~~
{'quiet': False, 'out_loc': None, 'use_gpu': False, 'pieces': 3, 'nb_epoch': 20, 'pooling': 'mean+max', 'dropout_decay': 0.0, 'dropout': 0.0, 'max_batch_size': 128, 'min_batch_size': 1, 'depth': 2, 'width': 64, 'dataset': 'quora'}
Load spaCy
Traceback (most recent call last):
  File "glove_mwe_multipool_predict.py", line 190, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "glove_mwe_multipool_predict.py", line 91, in main
    nlp = get_spacy('en')
  File "/usr/local/lib/python3.6/dist-packages/thinc/extra/load_nlp.py", line 11, in get_spacy
    SPACY_MODELS[lang] = spacy.load(lang, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 126, in load_model_from_link
    cls = import_file(name, path)
  File "/usr/local/lib/python3.6/dist-packages/spacy/compat.py", line 119, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/spacy/data/en/__init__.py'
~~~

Looking into the directory I do indeed do not find any init.py

~~~bash
$ ls /usr/local/lib/python3.6/dist-packages/spacy/data/en
deps  meta.json  ner  pos  vocab
~~~

All packages, including spacy, are up to date. The error is generated based on the latest git commit

**Comment by patvdleer** [comment]
I've fixed this by reinstalling the spacy package using `python3.6 -m spacy download en` instead of `spacy download en` directly since this used an older PY2.7 version.

But I am now running into a decode error which seems a py2 to 3 porting error.

`glove_mwe_multipool_siamese.py`
~~~
  File "glove_mwe_multipool_siamese.py", line 202, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "glove_mwe_multipool_siamese.py", line 151, in main
    train, dev = datasets.quora_questions()
  File "/usr/local/lib/python3.6/dist-packages/thinc/extra/datasets.py", line 190, in quora_questions
    sent1 = sent1.decode('utf8').strip()
AttributeError: 'str' object has no attribute 'decode'
~~~

I've fixed this (quick and dirty) by:
~~~python
ry:
                sent1 = sent1.decode('utf8').strip()
            except AttributeError:
                sent1 = sent1.strip()
            try:
                sent2 = sent2.decode('utf8').strip()
            except AttributeError:
                sent2 = sent2.strip()
~~~


`glove_mwe_multipool_predict.py`
~~~
{'quiet': False, 'out_loc': None, 'use_gpu': False, 'pieces': 3, 'nb_epoch': 20, 'pooling': 'mean+max', 'dropout_decay': 0.0, 'dropout': 0.0, 'max_batch_size': 128, 'min_batch_size': 1, 'depth': 2, 'width': 64, 'dataset': 'quora'}
Load spaCy
Construct model
Traceback (most recent call last):
  File "glove_mwe_multipool_predict.py", line 190, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "glove_mwe_multipool_predict.py", line 108, in main
    embed = StaticVectors('en', width)# + Embed(width, width*2, 5000)
  File "/usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/static_vectors.py", line 47, in __init__
    "Cannot create vectors table with dimension 0.\n"
ValueError: Cannot create vectors table with dimension 0.
If you're using pre-trained vectors, are the vectors loaded?
~~~

**Comment by ekeuus** [comment]
I seem to be running into the same "AttributeError: 'str' object has no attribute 'decode'" error. What was the final solution for you?

**Comment by patvdleer** [comment]
@ekeuus editing `/usr/local/lib/python3.6/dist-packages/thinc/extra/datasets.py` (with sudo) to the code above. Basically quick and dirty wrapping it in a try except

**Comment by honnibal** [comment]
That error should be fixed now --- sorry about the delay on this!

The examples still don't seem right though? I'm not sure if there's a bug or the hyper-parameters are bad.
