### ISSUE TITLE
Can't pickle nested function in FeatureExtracter

### ISSUE THREAD

**Issue by drfraser** [explosion/thinc#53]
spaCy: 2.0.9
thinc: 6.10.2
joblib: 0.11

I am testing out spaCy (thanks very much for the library - it was of great help in my dissertation) and tried to run the multi_processing.py example as I am having some trouble with processes and spaCy dying for no reason (or error message)...  My code runs fine when not using multiprocessing (I'm not using joblib), but breaks when I run spacy in a child process. So I wanted to see how using joblib works.  I expected multi_processing.py to run without any problems but got this:

Traceback (most recent call last):
  File "multi_processing.py", line 78, in <module>
    plac.call(main)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "multi_processing.py", line 42, in main
    executor(tasks)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/joblib/parallel.py", line 699, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/joblib/pool.py", line 371, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'

So in tracking down what is going on, and examining the thinc source code, it is obvious the nested functions in thinc.api.FeatureExtracter are the issue.  No idea of what to do, but am filing this as the issues raised in spaCy (#1862, #1669) do not mention any related issues in thinc and I don't see anything here.

https://stackoverflow.com/questions/12019961/python-pickling-nested-functions

**Comment by honnibal** [comment]
Thanks! Fixed.

**Comment by millertracy** [comment]
spaCy: 2.0.12
thinc: 6.10.2
joblib: 0.11

   I recently experienced the same problem as above. I just updated thinc to 6.11.2 to fix the pickle error associated with thinc.api.FeatureExtracter. However with this new updated thinc version, i get a new error:

`AttributeError: Can't pickle local object 'with_flatten.<locals>.begin_update'`

**Comment by Dobatymo** [comment]
I have got the same problem `Reason: 'AttributeError("Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'",)'`
