### ISSUE TITLE
numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by mareksuscak** [explosion/thinc#629]
I wasn't sure where this error was coming from so please let me know if this needs to be reported in another repository. We're using `apache-beam`, `spacy`, and `sentence-transformers` in a data pipeline. When I install all dependencies and run the pipeline, it fails with the following stack trace printed in the terminal:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ds/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ds/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/marek/Projects/iterate/signals-data/pipelines/iterate/enrichment/__main__.py", line 25, in <module>
    from pipelines.shared.transforms import AddEmbeddings
  File "/Users/marek/Projects/iterate/signals-data/pipelines/shared/transforms.py", line 3, in <module>
    import spacy
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ds/lib/python3.9/site-packages/spacy/__init__.py", line 11, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ds/lib/python3.9/site-packages/thinc/api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ds/lib/python3.9/site-packages/thinc/initializers.py", line 4, in <module>
    from .backends import Ops
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ds/lib/python3.9/site-packages/thinc/backends/__init__.py", line 8, in <module>
    from .cupy_ops import CupyOps, has_cupy
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ds/lib/python3.9/site-packages/thinc/backends/cupy_ops.py", line 19, in <module>
    from .numpy_ops import NumpyOps
  File "thinc/backends/numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

I think this error is coming from `thinc` because it incorrectly reports the supported version range for `numpy`. When I force install `numpy 1.22.x` by running `pip install numpy==1.22.1` the pipeline works. I don't have a lot of expertise with Python development and I could use some community/maintainer help. There was a [related issue reported in this repo](https://github.com/explosion/thinc/issues/515) some time ago and so I think we need to find a definite solution.

Here's our dependency tree:

```
apache-beam==2.37.0
  cloudpickle==2.0.0
  crcmod==1.7
  dill==0.3.1.1
  fastavro==1.4.10
  grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  hdfs==2.7.0
    docopt==0.6.2
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  httplib2==0.19.1
    pyparsing==2.4.7
  numpy==1.21.5
  oauth2client==4.1.3
    httplib2==0.19.1
      pyparsing==2.4.7
    pyasn1==0.4.8
    pyasn1-modules==0.2.8
      pyasn1==0.4.8
    rsa==4.8
      pyasn1==0.4.8
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  orjson==3.6.7
  proto-plus==1.20.3
    protobuf==3.19.4
  protobuf==3.19.4
  pyarrow==6.0.1
    numpy==1.21.5
  pydot==1.4.2
    pyparsing==2.4.7
  pymongo==3.12.3
  python-dateutil==2.8.2
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  pytz==2022.1
  requests==2.27.1
    certifi==2021.10.8
    charset-normalizer==2.0.12
    idna==3.3
    urllib3==1.26.9
  typing_extensions==4.1.1
beautifulsoup4==4.10.0
  soupsieve==2.3.1
elasticsearch==7.17.1
  certifi==2021.10.8
  urllib3==1.26.9
google-apitools==0.5.31
  fasteners==0.17.3
  httplib2==0.19.1
    pyparsing==2.4.7
  oauth2client==4.1.3
    httplib2==0.19.1
      pyparsing==2.4.7
    pyasn1==0.4.8
    pyasn1-modules==0.2.8
      pyasn1==0.4.8
    rsa==4.8
      pyasn1==0.4.8
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
google-cloud-bigquery==2.34.3
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  google-cloud-core==1.7.2
    google-api-core==1.31.5
      google-auth==1.35.0
        cachetools==4.2.4
        pyasn1-modules==0.2.8
          pyasn1==0.4.8
        rsa==4.8
          pyasn1==0.4.8
        setuptools==61.3.0
        six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
      googleapis-common-protos==1.56.0
        protobuf==3.19.4
      packaging==21.3
        pyparsing==2.4.7
      protobuf==3.19.4
      pytz==2022.1
      requests==2.27.1
        certifi==2021.10.8
        charset-normalizer==2.0.12
        idna==3.3
        urllib3==1.26.9
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  google-resumable-media==2.3.2
    google-crc32c==1.3.0
  grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  packaging==21.3
    pyparsing==2.4.7
  proto-plus==1.20.3
    protobuf==3.19.4
  protobuf==3.19.4
  python-dateutil==2.8.2
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  requests==2.27.1
    certifi==2021.10.8
    charset-normalizer==2.0.12
    idna==3.3
    urllib3==1.26.9
google-cloud-bigquery-storage==2.13.0
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  proto-plus==1.20.3
    protobuf==3.19.4
google-cloud-bigtable==1.7.0
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  google-cloud-core==1.7.2
    google-api-core==1.31.5
      google-auth==1.35.0
        cachetools==4.2.4
        pyasn1-modules==0.2.8
          pyasn1==0.4.8
        rsa==4.8
          pyasn1==0.4.8
        setuptools==61.3.0
        six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
      googleapis-common-protos==1.56.0
        protobuf==3.19.4
      packaging==21.3
        pyparsing==2.4.7
      protobuf==3.19.4
      pytz==2022.1
      requests==2.27.1
        certifi==2021.10.8
        charset-normalizer==2.0.12
        idna==3.3
        urllib3==1.26.9
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  grpc-google-iam-v1==0.12.3
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
google-cloud-datastore==1.15.3
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  google-cloud-core==1.7.2
    google-api-core==1.31.5
      google-auth==1.35.0
        cachetools==4.2.4
        pyasn1-modules==0.2.8
          pyasn1==0.4.8
        rsa==4.8
          pyasn1==0.4.8
        setuptools==61.3.0
        six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
      googleapis-common-protos==1.56.0
        protobuf==3.19.4
      packaging==21.3
        pyparsing==2.4.7
      protobuf==3.19.4
      pytz==2022.1
      requests==2.27.1
        certifi==2021.10.8
        charset-normalizer==2.0.12
        idna==3.3
        urllib3==1.26.9
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
google-cloud-dlp==3.6.2
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  proto-plus==1.20.3
    protobuf==3.19.4
  pytz==2022.1
google-cloud-language==1.3.0
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
google-cloud-pubsublite==1.4.1
  google-cloud-pubsub==2.11.0
    google-api-core==1.31.5
      google-auth==1.35.0
        cachetools==4.2.4
        pyasn1-modules==0.2.8
          pyasn1==0.4.8
        rsa==4.8
          pyasn1==0.4.8
        setuptools==61.3.0
        six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
      googleapis-common-protos==1.56.0
        protobuf==3.19.4
      packaging==21.3
        pyparsing==2.4.7
      protobuf==3.19.4
      pytz==2022.1
      requests==2.27.1
        certifi==2021.10.8
        charset-normalizer==2.0.12
        idna==3.3
        urllib3==1.26.9
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    grpc-google-iam-v1==0.12.3
      googleapis-common-protos==1.56.0
        protobuf==3.19.4
      grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
        six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    grpcio-status==1.45.0
      googleapis-common-protos==1.56.0
        protobuf==3.19.4
      grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
        six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
      protobuf==3.19.4
    proto-plus==1.20.3
      protobuf==3.19.4
  grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  grpcio-status==1.45.0
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    protobuf==3.19.4
  overrides==6.1.0
    typing-utils==0.1.0
google-cloud-recommendations-ai==0.2.0
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  proto-plus==1.20.3
    protobuf==3.19.4
google-cloud-spanner==1.19.1
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  google-cloud-core==1.7.2
    google-api-core==1.31.5
      google-auth==1.35.0
        cachetools==4.2.4
        pyasn1-modules==0.2.8
          pyasn1==0.4.8
        rsa==4.8
          pyasn1==0.4.8
        setuptools==61.3.0
        six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
      googleapis-common-protos==1.56.0
        protobuf==3.19.4
      packaging==21.3
        pyparsing==2.4.7
      protobuf==3.19.4
      pytz==2022.1
      requests==2.27.1
        certifi==2021.10.8
        charset-normalizer==2.0.12
        idna==3.3
        urllib3==1.26.9
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
  grpc-google-iam-v1==0.12.3
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
google-cloud-videointelligence==1.16.1
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
google-cloud-vision==1.0.0
  google-api-core==1.31.5
    google-auth==1.35.0
      cachetools==4.2.4
      pyasn1-modules==0.2.8
        pyasn1==0.4.8
      rsa==4.8
        pyasn1==0.4.8
      setuptools==61.3.0
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
    googleapis-common-protos==1.56.0
      protobuf==3.19.4
    packaging==21.3
      pyparsing==2.4.7
    protobuf==3.19.4
    pytz==2022.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    setuptools==61.3.0
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
grpcio-gcp==0.2.2
  grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1648220738213/work
    six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
pipdeptree==2.2.1
  pip==22.0.4
sentence-transformers==2.2.0
  huggingface-hub==0.4.0
    filelock==3.6.0
    packaging==21.3
      pyparsing==2.4.7
    PyYAML==6.0
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    tqdm==4.63.1
    typing_extensions==4.1.1
  nltk==3.7
    click==8.0.4
    joblib==1.1.0
    regex==2022.3.15
    tqdm==4.63.1
  numpy==1.21.5
  scikit-learn==1.0.2
    joblib==1.1.0
    numpy==1.21.5
    scipy==1.8.0
      numpy==1.21.5
    threadpoolctl==3.1.0
  scipy==1.8.0
    numpy==1.21.5
  sentencepiece==0.1.96
  torch==1.11.0
    typing_extensions==4.1.1
  torchvision==0.12.0
    numpy==1.21.5
    Pillow==9.0.1
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    torch==1.11.0
      typing_extensions==4.1.1
    typing_extensions==4.1.1
  tqdm==4.63.1
  transformers==4.17.0
    filelock==3.6.0
    huggingface-hub==0.4.0
      filelock==3.6.0
      packaging==21.3
        pyparsing==2.4.7
      PyYAML==6.0
      requests==2.27.1
        certifi==2021.10.8
        charset-normalizer==2.0.12
        idna==3.3
        urllib3==1.26.9
      tqdm==4.63.1
      typing_extensions==4.1.1
    numpy==1.21.5
    packaging==21.3
      pyparsing==2.4.7
    PyYAML==6.0
    regex==2022.3.15
    requests==2.27.1
      certifi==2021.10.8
      charset-normalizer==2.0.12
      idna==3.3
      urllib3==1.26.9
    sacremoses==0.0.49
      click==8.0.4
      joblib==1.1.0
      regex==2022.3.15
      six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
      tqdm==4.63.1
    tokenizers==0.11.6
    tqdm==4.63.1
spacy==3.2.4
  blis==0.7.7
    numpy==1.21.5
  catalogue==2.0.7
  click==8.0.4
  cymem==2.0.6
  Jinja2==3.1.1
    MarkupSafe==2.1.1
  langcodes==3.3.0
  murmurhash==1.0.6
  numpy==1.21.5
  packaging==21.3
    pyparsing==2.4.7
  pathy==0.6.1
    smart-open==5.2.1
    typer==0.4.1
      click==8.0.4
  preshed==3.0.6
    cymem==2.0.6
    murmurhash==1.0.6
  pydantic==1.8.2
    typing_extensions==4.1.1
  requests==2.27.1
    certifi==2021.10.8
    charset-normalizer==2.0.12
    idna==3.3
    urllib3==1.26.9
  setuptools==61.3.0
  spacy-legacy==3.0.9
  spacy-loggers==1.0.2
    wasabi==0.9.1
  srsly==2.4.2
    catalogue==2.0.7
  thinc==8.0.15
    blis==0.7.7
      numpy==1.21.5
    catalogue==2.0.7
    cymem==2.0.6
    murmurhash==1.0.6
    numpy==1.21.5
    preshed==3.0.6
      cymem==2.0.6
      murmurhash==1.0.6
    pydantic==1.8.2
      typing_extensions==4.1.1
    setuptools==61.3.0
    srsly==2.4.2
      catalogue==2.0.7
    wasabi==0.9.1
  tqdm==4.63.1
  typer==0.4.1
    click==8.0.4
  wasabi==0.9.1
wheel==0.37.1

```

**Comment by adrianeboyd** [comment]
I'm going to take a guess that you're running this on an M1? And also, the tracebacks include miniforge, are you installing some packages from `conda-forge` instead of with `pip`? (There's a slight chance it's related to differences between the numpy versions used during builds for pip/pypi than for conda-forge, but I initially don't think so based on what you've reported.)

In general, this can happen if you build packages like thinc from source (which defaults to the newest numpy in an isolated build environment) and then at a later point some other package (or your own requirements in this case) downgrades numpy in your runtime environment.

As mentioned in linked PR, the solution is to use build constraints:

```shell
PIP_CONSTRAINT=constraints.txt pip install -r requirements.txt
```

E.g.: https://raw.githubusercontent.com/explosion/thinc/master/build-constraints.txt

These constraints are what we use for our published pypi wheels to match the oldest available numpy wheels for x86_64 for each version of python, but you can pick the build requirements that make sense for your code/environment. It works as long as the version of numpy in the build constraints is the same or older than the runtime numpy.

For suggestions for numpy build constraints beyond x86_64, you can take a look at the `oldest-supported-numpy` constraints:

https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg

In order to straighten out everything in a new environment you can use `pip install --no-cache-dir` so that it doesn't use any cached wheels that you built previously with other versions of numpy. Once you settle on build constraints for your projects, you can delete your whole pip cache and then run `pip install` normally so your cache contains the versions you'd want in the future.

And don't try to use `pip install -c` instead, it doesn't propagate to the isolated build environments.

Yes, this is all kind of terrible and broken with pip, and it's a place where conda-forge is better. If you're already using conda, for spacy and its dependencies, it could be easier to use the conda-forge packages instead of compiling from source with pip. Install as many packages as available from conda-forge, which will all be compatible with each other, and then install the remainder with pip, still with build constraints if anything is compiled. There are osx arm64 conda-forge packages for all recent releases of our libraries.

**Comment by mareksuscak** [comment]
@adrianeboyd that's correct, I'm running it on an M1 which is why I use Conda since some packages are still not ARM-compatible and you're also right that there's one package that is installed from `conda-forge` - it's `grpcio` but this one makes no use of `numpy` as far as I understand. All other packages are installed via pip.

**Comment by adrianeboyd** [comment]
Right, so if you want to install spacy with pip, try this with the `PIP_CONSTRAINT` and `--no-cache-dir` like I described above.

Or you can use `conda install` for the spacy requirements instead if you want.

**Comment by mareksuscak** [comment]
I can confirm that the solution you suggested above worked. I've used the following `build-constraints.txt`:

```
# build version constraints for use with wheelwright + multibuild
# https://github.com/explosion/thinc/issues/629#issuecomment-1087167085
numpy==1.21.5
```

Then used the following command to build in a brand new conda environment:

```
PIP_CONSTRAINT=build-constraints.txt pip --no-cache-dir install -r requirements.txt
```

Do we want to document it for everyone else in the README?

**Comment by adrianeboyd** [comment]
I should have mentioned: if you are running this on a M1, you should also want to include the package `thinc-apple-ops`, everything will be much much faster. Even if you use conda, install `thinc-apple-ops` with `pip` in addition.

We'll think about how we can add this to the README while keeping the standard install instructions clear enough. It is definitely frustrating.
